import error by l3_odl
tox -e py27 fails as follows.
This is because importing common_db_mixin from db_base_plugin_v2 was removed,
by the change set of ece8cc2e9aae1610a325d0c206e38da3da9a0a1a,
by the change id of I1eac61c258541bca80e14be4b7c75519a014ffae

The log from here

  /networking-odl $ tox -e py27
  py27 create: /networking-odl/.tox/py27
  py27 installdeps: -r/networking-odl/test-requirements.txt

  py27 develop-inst: /networking-odl
  py27 runtests: PYTHONHASHSEED='3892857836'
  py27 runtests: commands[0] | bash tools/pretty_tox.sh
  WARNING:test command found but not installed in testenv
    cmd: /bin/bash
    env: /networking-odl/.tox/py27
  Maybe forgot to specify a dependency?
  running testr
  No handlers could be found for logger "neutron.quota"
  Non-zero exit code (2) from test listing.
  error: testr failed (3)
  running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
  OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
  OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
  OS_LOG_CAPTURE=1 \
  ${PYTHON:-python} -m subunit.run discover -t ./ . --list
  --- import errors ---
  Failed to import test module: networking_odl.tests.unit.l3.test_l3_odl
  Traceback (most recent call last):
    File "/networking-odl/.tox/py27/local/lib/python2.7/site-packages/unittest2/loader.py", line 445, in _find_test_path
      module = self._get_module_from_name(name)
    File "/networking-odl/.tox/py27/local/lib/python2.7/site-packages/unittest2/loader.py", line 384, in _get_module_from_name
      __import__(name)
    File "networking_odl/tests/unit/l3/test_l3_odl.py", line 22, in <module>
      from networking_odl.l3 import l3_odl
    File "networking_odl/l3/l3_odl.py", line 40, in <module>
      db_base_plugin_v2.common_db_mixin.CommonDbMixin,
  AttributeError: 'module' object has no attribute 'common_db_mixin'
  The test run didn't actually run any tests
  ERROR: InvocationError: '/bin/bash tools/pretty_tox.sh '
  ___________________________________ summary ____________________________________
  ERROR:   py27: commands failed

Closes-Bug: #1463544
Change-Id: Ifd6316420b743358c6f568cb925357f61223c92d